before_script:
  - gem install bundler
  - bundle install
  - bundle exec rake db:create

rspec:
  test: "rake spec"
  tags:
    - ruby
    - postgres
  only:
    - branches

staging:
  deploy: "cap stating deploy"
  tags:
    - capistrano
    - ubuntu
  except:
    - stable

production:
  deploy:
    - cap production deploy
    - cap notify
  tags:
    - capistrano
    - ubuntu
  only:
    - master
    - /^deploy-.*$/